# Generated by Django 5.0.3 on 2024-04-26 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_remove_companies_id_companies_website_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='logo',
            field=models.ImageField(default='company_logos/default_image.png', upload_to='company_logo/'),
        ),
    ]
